name: Commandspy
main: me.korikisulda.commandspy.commandspy
version: 2.0.0
description: >
             A - er - simple? plugin to tell you what everyone's doing.
commands:
    commandspy:
      description: Access commandspy subcommands
      usage: /commandspy help
softdepend: [WorldEdit]
